448 improved Github actions
apache/flagon-useralejs pull request #456
Opened 2024-05-16 14:58 UTC by rc10house

Adds improved github actions for CI/CD. Specifically linting, formatting, and automatic license checking. Still will need to add type checking, automatic release notes, and cronjobs for triggering release candidates in the future.

2024-05-20 13:42 UTC, EandrewJones requested changes

2024-05-20 13:42 UTC, EandrewJones commented on .github/workflows/node.js.yml
> +      - 448-improve-GH-actions #TODO: remove this
This needs to be removed, no?

2024-05-20 13:42 UTC, EandrewJones commented on .github/workflows/node.js.yml
> +      # TODO: add skywalking-eyes for licensing
Needs to be removed.

2024-05-20 13:42 UTC, EandrewJones commented on .github/workflows/node.js.yml
> +  CI-tests:
Can we:
1) treat linting+type checking and building+testing as two different jobs
2) Label steps with names

See [ECharts GH actions](https://github.com/apache/echarts/blob/master/.github/workflows/ci.yml), for example.

2024-05-21 15:24 UTC, rc10house commented
Resolved requested changes

2024-05-21 15:30 UTC, rc10house commented
Made requested changes

2024-05-21 17:30 UTC, EandrewJones approved these changes

2024-05-21 19:06 UTC, merged