Added websockets for sending logs if available
apache/flagon-useralejs pull request #489
Opened 2024-08-19 19:17 UTC by rc10house

Adds functionality to `main.ts` to check if the provided `config.url` is running a WebSocket server. If so, we upgrade the connection to send data over WebSockets and use this for sending all logs. If not, we send data with the existing REST functionality. I also added a test/example WebSockets server `examples/ws-server.js`. 

Note: WebSockets will not run when using Jest to test currently, so the application skips attempting to create a WebSockets connection if it detects running in a test environment (headless browser). 

Closes: #444

2024-08-19 20:16 UTC, Jyyjy requested changes

2024-08-19 20:16 UTC, Jyyjy commented on src/main.ts
> +getWebsocketsEnabled(config);
Move this call to getInitialSettings()

2024-08-19 20:16 UTC, Jyyjy commented on src/main.ts
Move all the changes in this file to getInitialSettings.ts

2024-08-19 20:16 UTC, Jyyjy commented on example/test-client.ts
Can you move the testing logic to test/ and add the test to at least one of the frameworks (Jest for unit/, Playwright for e2e/). e2e may be easier, because it uses a real(ish) browser and allows control over the receiving server in playwright.config.ts.

2024-08-19 21:20 UTC, rc10house commented on example/test-client.ts
Yes, though it may have to be Playwright only because I could not get any Websockets to work with Jest. May be a bug but I'm not sure.

2024-08-21 20:24 UTC, rc10house commented
Had to separate some tests to avoid websockets being ran from within `jsdom` environment. Also had to add some helper methods for manually turning on/off websockets for testing purposes.

2024-08-29 16:44 UTC, Jyyjy commented
You can add another webserver to test/e2e/playwright.config.ts and specify which webserver to use for different projects. Set existing projects to use the existing webserver, and create a new project with a websocket server.

I would set http and websockets to different ports within the same server and specify "reuseExistingServer: True"

Relevant docs:
https://playwright.dev/docs/test-webserver

2024-10-09 16:54 UTC, EandrewJones commented
@rc10house Bumping this. Would be nice to get this over the finish line if you have time.

2024-10-16 18:12 UTC, Jyyjy approved these changes
Good test coverage, thanks for being persistent. For my own understanding, what's the difference between jest specs that have "@jest-environment jsdom" and those that don't?

2024-10-16 18:29 UTC, rc10house commented
@Jyyjy for some reason, the previous jest-environment specification (in `package.json`) lead to some of the tests using node as the environment anyway. Node would then throw errors because it tries to use `ws` module, which is not available in the browser. I added the `@jest-environment jsdom` individually to avoid these errors.

2024-10-16 18:30 UTC, rc10house commented
@Jyyjy the specific tests with the added `@jest-environment jsdom` were the ones throwing the node errors.

2024-10-16 19:11 UTC, Jyyjy commented
@EandrewJones gonna leave this up for a couple days in case you want to review, if not I'll merge.

2024-10-16 19:39 UTC, merged